// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf4nJZFA_FSSKwnWG_7Qnx1YLKujLsKq4',
    appId: '1:137756708809:android:ac551cdd73bc332c8aa218',
    messagingSenderId: '137756708809',
    projectId: 'pethub-e6a26',
    storageBucket: 'pethub-e6a26.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1LVI7MrfLDgQKYA6U5EHRo4teYvjZMhc',
    appId: '1:137756708809:web:a17abce2864799788aa218',
    messagingSenderId: '137756708809',
    projectId: 'pethub-e6a26',
    authDomain: 'pethub-e6a26.firebaseapp.com',
    storageBucket: 'pethub-e6a26.firebasestorage.app',
    measurementId: 'G-R6V3D2YQP0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF2RLw7Uo-TEG4bp4Cky6NWDcYi2lxtfs',
    appId: '1:137756708809:ios:9dc7813050d110a08aa218',
    messagingSenderId: '137756708809',
    projectId: 'pethub-e6a26',
    storageBucket: 'pethub-e6a26.firebasestorage.app',
    iosBundleId: 'com.example.pethubApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF2RLw7Uo-TEG4bp4Cky6NWDcYi2lxtfs',
    appId: '1:137756708809:ios:9dc7813050d110a08aa218',
    messagingSenderId: '137756708809',
    projectId: 'pethub-e6a26',
    storageBucket: 'pethub-e6a26.firebasestorage.app',
    iosBundleId: 'com.example.pethubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1LVI7MrfLDgQKYA6U5EHRo4teYvjZMhc',
    appId: '1:137756708809:web:b86b082ef647841b8aa218',
    messagingSenderId: '137756708809',
    projectId: 'pethub-e6a26',
    authDomain: 'pethub-e6a26.firebaseapp.com',
    storageBucket: 'pethub-e6a26.firebasestorage.app',
    measurementId: 'G-D9NM5QL5CR',
  );
}
